- name: remove default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Template a file
  template:
    src: test.com.j2
    dest: /etc/nginx/sites-enabled/test.com
    owner: "{{ nginx.user }}"
    group: "{{ nginx.user }}"
    mode: "0644"

- name: restart nginx service
  service:
    name: nginx
    state: started

    
