---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu_image
    image: geerlingguy/docker-ubuntu2004-ansible
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
verifier:
  name: testinfra
  lint:
    name: flake8
 